artifacts_root: artifacts

data ingestion:
  root dir: artifacts/data_ingestion
  source: data
  data_dir: artifacts/data_ingestion/train.csv
  STATUS_FILE: artifacts/data_ingestion/status.txt

data validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/train.csv/train.csv
  STATUS_FILE: artifacts/data_validation/status.txt  # status of data validation 




feature_engineering:
  root_dir: artifacts/feature_engineering
  train_data_path: artifacts/cross_val/data_for_final_train
  test_data_path: artifacts/cross_val/data_for_final_train
  STATUS_FILE: artifacts/feature_engineering/status.txt

cross_val:
  root_dir: artifacts/cross_val
  extracted_features: artifacts/cross_val/extracted_features  # Directory for extracted features
  model_cache_rf: artifacts/cross_val/model_cache_rf  # Cache for models
  train_data_path: artifacts/cross_val/train_data.npz  # Train data path
  test_data_path: artifacts/cross_val/test_data.npz  # Test data path
  metric_file_name_rf: artifacts/cross_val/metrics.json  # Metrics for K-Fold CV
  best_model_params_rf: artifacts/cross_val/best_model_params.json  # Best parameters for K-Fold CV
  STATUS_FILE: artifacts/cross_val/status.txt  # Status of cross-validation


model_trainer:
  root_dir: artifacts/model_trainer  # Root directory for model trainer artifacts
  train_data_path: artifacts/cross_val/train_data.npz  # Train data path from cross-validation
  test_data_path: artifacts/cross_val/test_data.npz  # Test data path from cross-validation
  final_model_name: artifacts/model_trainer/final_model.joblib  # Final trained model file
  metric_file_name_rf: artifacts/cross_val/metrics.json  # Metrics for K-Fold cross-validation
  best_model_params_rf: artifacts/cross_val/best_model_params.json  # Best model parameters from K-Fold
  STATUS_FILE: artifacts/model_trainer/status.txt  # Status file for training process


model_evaluation:
  root_dir: artifacts/model_evaluation  # Root directory for evaluation artifacts
  test_data_path: artifacts/cross_val/test_data.npz  # Test data path from cross-validation
  model_path: artifacts/model_trainer/final_model.joblib  # Final trained model path
  metric_file: artifacts/model_evaluation/metrics.json  # Evaluation metrics file
  STATUS_FILE: artifacts/model_evaluation/status.txt  # Status file for evaluation process


