# Not required in this project for the time being.
FEATURES_DATA_TYPES:

  Item_Identifier  : object
  Item_Weight      : float64
  Item_Fat_Content : object
  Item_Visibility  : float64
  Item_Type        : object
  Item_MRP         : float64
  Outlet_Identifier: object
  Outlet_Size      : object
  Outlet_Type      : object
  Item_Outlet_Sales: float64
  Outlet_Location_Type: object
  Outlet_Establishment_Year: int64

Target_column:
   target_column_name:Item_Outlet_Sales  